CREATE TABLE USUARIOS (
id BIGINT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(100) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
contrasena VARCHAR(300) NOT NULL,
activo TINYINT NOT NULL,
PRIMARY KEY (id)
);